name: Cloud Transfer Workflow

on:

  workflow_dispatch:

    inputs:

      url:

        description: 'Download Url'

        required: true

        default: ''

      headers:

        description: 'Download Headers'

        required: true

        default: 'Accept-Language:zh-CN,zh;q=0.9'
        
      cookie:

        description: 'User Cookie'

        required: false

        default: ''
        
      

jobs:

  download:

    runs-on: ubuntu-latest

    steps:
     - name: Checkout
       uses: actions/checkout@v1
     - name: Set up Python 3.7
       uses: actions/setup-python@v1
       with:
        python-version: 3.7    
     - run: |
        pip install requests
        python download.py ${{ github.event.inputs.url }} ${{ github.event.inputs.cookie}} ${{ github.event.inputs.headers }}
